# Generated by Django 3.0.7 on 2020-06-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mydata',
            table="'User_Table'",
        ),
    ]
