# Generated by Django 3.0.7 on 2020-06-27 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200625_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 27, 19, 21, 24, 918408, tzinfo=utc), max_length=50),
        ),
        migrations.AddField(
            model_name='mydata',
            name='verification_code',
            field=models.CharField(default='123', max_length=10),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='mydata',
            table="'User'",
        ),
    ]
