# Generated by Django 3.0.7 on 2020-06-27 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200627_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 27, 19, 22, 54, 166305), max_length=50),
        ),
    ]
