# Generated by Django 3.0.7 on 2020-06-27 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200627_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 19, 24, 56, 762995, tzinfo=utc)),
        ),
    ]
