# Generated by Django 3.0.7 on 2020-06-27 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200627_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 27, 19, 28, 13, 909175, tzinfo=utc)),
        ),
    ]
