# Generated by Django 3.0.7 on 2020-06-27 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200627_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
