# Generated by Django 3.0.7 on 2020-06-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20200627_1929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mydata',
            table='User',
        ),
    ]
